# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180129_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='姓名'),
        ),
    ]
